#!/bin/bash
alias ls='ls --color'

function splash {
  local art=( $(ls /home/art) )
  cat /home/art/${art[ $(( RANDOM % ${#art[@]} )) ]}
}

printf '** Welcome to the Super Star Trek Docker container! **\n\n'
splash
printf '\n\nTo play SST just type: ./sst\n\n'
