#!/bin/bash
export WINEPREFIX="$HOME/.PlayOnLinux/wineprefix/Games/"
export WINEARCH=win32
export WINE="/opt/wine-staging/bin/wine"
export LIBGL_ALWAYS_SOFTWARE=1 

alias ls='ls --color'

cat /home/splash.txt

INSTALLDIR="/root/.PlayOnLinux/wineprefix/Games/drive_c/Program Files/Empire Earth/"
if [ -d "${INSTALLDIR}" ]
then
	printf "\n\n
		Path to EE original : \"${INSTALLDIR}/Empire Earth\"
		Path to EE expansion: \"${INSTALLDIR}/Empire Earth - The Art of Conquest\"
		 
		To play Empire Earth:
			1. Move to game directory     : '# cd DIR'
			2. Launch executable with wine: '# wine GAME.exe'
		\n\n"
else
	printf "\n\n
                The rest of the install needs to be done manually after being launched with correct envars and whatnot (GUI stuff)
                See gist: https://gist.github.com/ErezBinyamin/6199e8fe1388c0521d6398e380641cdf

                To start installation:
                        1. Move to install directory : '# cd /root'
                        2. Run install script        : '# ./EE2-Linux-Install.bash'
                        3. Get container ID          : '# CONTAINER_ID=\$(docker ps | grep ee2wine | cut -d' ' -f1)'
                        4. Save installed state      : '# docker commit CONTAINER_ID ee2wine:installed'
                \n\n"
fi

